### ISSUE TITLE
repository.toml: Support more than one compose entry

### ISSUE THREAD

**Issue by ericof** [plone/repoplone#5]
Today:

```toml
[repository]
name = "fake-distribution"
managed_by_uv = true
changelog = "CHANGELOG.md"
version = "version.txt"
compose = "docker-compose.yml"
```

Future:

```toml
[repository]
name = "fake-distribution"
managed_by_uv = true
changelog = "CHANGELOG.md"
version = "version.txt"
compose = ["docker-compose.yml", "docker-compose-dev.yml"]
```
