### ISSUE TITLE
repository.toml: Deprecate `managed_by_uv` setting

### ISSUE THREAD

**Issue by ericof** [plone/repoplone#6]
Today:

```toml
[repository]
...
managed_by_uv = true

```

Use the setting from `backend/pyproject.toml`
